config/routes.rb
Rails.application.routes.draw do
  get 'admin_users/delete'

  get 'admin_users/edit'

  get 'admin_users/index'

  get 'admin_users/new'

  get 'access/index'

  get 'access/login'

  get 'public/index'

  resources :quick_specs
  resources :general_specs
  resources :vehicles
  resources :categories
  resources :manufacturers
  devise_for :admin_users
  devise_for :users

  root "public#index"

end

app/controllers/access_controller.rb
class AccessController < ApplicationController

  layout 'admin'

  before_action :confirm_logged_in, :except => [:login, :attempt_login, :logout]

def index
  #   display text & links
end

def login
  #   login form
end

def attempt_login
  if params[:email].present? && params[:password].present?
    found_user = AdminUser.where(:email => params[:email]).first
    if found_user
      authorized_user = found_user.authenticate(params[:password])
    end
  end
  if authorized_user
    session[:user_id] = authorized_user.id
    session[:email] = authorized_user.email
    flash[:notice] = 'You are now logged in.'
    redirect_to(action: 'index')
  else
    flash[:notice] = 'Invalid username/password combination.'
    redirect_to(action: 'login')
  end
end

def logout
  session[:user_id] = nil
  session[:email] = nil
  flash[:notice] = 'Logged out'
  redirect_to(action: 'login')
end

end

app/helpers/access_helper.rb
module AccessHelper
end

app/views/access/index.html.erb
<% @page_title = 'Admin Menu' %>

<div class ="menu">
  <h2>Admin Menu</h2>
  <div class="identity"> Logged in as: <%= session[:username] %></div>
  <ul>
    <li><%= link_to 'Manage Vehicles', vehicles_path %></li>
    <li><%= link_to 'Manage Categories', categories_path %></li>
    <li><%= link_to 'Manage Manufacturers', manufacturers_path %></li>
    <li><%= link_to 'Manage Admin Users', admin_users_index_path %></li>
    <!--<li><%#= link_to 'Manage Users', user %></li>-->
    <!--TODO: Add Manage Users Section-->
    <li><%= link_to 'Manage Manufacturers', manufacturers_path %></li>
    <!--<li><%#= link_to("Manage Pages", :controller => 'pages') %></li>-->
    <!--<li><%#= link_to("Manage Sections", :controller => 'sections') %></li>-->
    <li><%= link_to("Logout", :action => 'logout') %></li>
  </ul>
</div>

app/views/access/login.html.erb
<% @page_title = "Admin Login" %>

<div class="login">
  <%= form_tag(:action => 'attempt_login') do %>
      <table>
        <tr>
          <td><%= label_tag(:email) %></td>
          <td><%= text_field_tag(:email) %></td>
        </tr>
        <tr>
          <td><%= label_tag(:password) %></td>
          <td><%= password_field_tag(:password) %></td>
        </tr>
        <tr>
          <td>&nbsp;</td>
          <td><%= submit_tag('Log In') %></td>
        </tr>
      </table>
  <% end %>
</div>