config/routes.rb
Rails.application.routes.draw do
  get 'admin_users/delete'

  get 'admin_users/edit'

  get 'admin_users/index'

  get 'admin_users/new'

  get 'access/index'

  get 'access/login'

  get 'public/index'

  resources :quick_specs
  resources :general_specs
  resources :vehicles
  resources :categories
  resources :manufacturers
  devise_for :admin_users
  devise_for :users

  root "public#index"

end

app/models/general_spec.rb
class GeneralSpec < ActiveRecord::Base
  belongs_to :vehicle

  # acts_as_list :scope => :vehicle
  #TODO: add acts_as_list gem

  after_save :touch_vehicle

  private

  def touch_vehicle
    # touch is similar to:
    # subject.update_attribute(:updated_at, Time.now)
    vehicle.touch
  end
end

app/controllers/general_specs_controller.rb
class GeneralSpecsController < ApplicationController

  layout 'admin'

  before_action :confirm_logged_in
  before_action :set_general_spec, only: [:show, :edit, :update, :destroy]

  # GET /general_specs
  # GET /general_specs.json
  def index
    @general_specs = GeneralSpec.all
  end

  # GET /general_specs/1
  # GET /general_specs/1.json
  def show
  end

  # GET /general_specs/new
  def new
    @general_spec = GeneralSpec.new
  end

  # GET /general_specs/1/edit
  def edit
  end

  # POST /general_specs
  # POST /general_specs.json
  def create
    @general_spec = GeneralSpec.new(general_spec_params)

    respond_to do |format|
      if @general_spec.save
        format.html { redirect_to @general_spec, notice: 'General spec was successfully created.' }
        format.json { render :show, status: :created, location: @general_spec }
      else
        format.html { render :new }
        format.json { render json: @general_spec.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /general_specs/1
  # PATCH/PUT /general_specs/1.json
  def update
    respond_to do |format|
      if @general_spec.update(general_spec_params)
        format.html { redirect_to @general_spec, notice: 'General spec was successfully updated.' }
        format.json { render :show, status: :ok, location: @general_spec }
      else
        format.html { render :edit }
        format.json { render json: @general_spec.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /general_specs/1
  # DELETE /general_specs/1.json
  def destroy
    @general_spec.destroy
    respond_to do |format|
      format.html { redirect_to general_specs_url, notice: 'General spec was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_general_spec
      @general_spec = GeneralSpec.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def general_spec_params
      params.require(:general_spec).permit(:manufacturer_id, :vehicle_id, :category_id, :engine_type, :engine_displacement, :bore_stroke, :cooling, :compression_ratio, :fuel_system, :ignition, :starting_system, :transmission, :final_drive, :rake_trail, :seat_height, :wheelbase, :front_suspension, :rear_suspension, :front_brake, :rear_brake, :front_tire, :rear_tire, :fuel_capacity, :dry_weight, :msrp)
    end
end

app/helpers/general_specs_helper.rb
module GeneralSpecsHelper
end

app/views/general_specs/_form.html.erb
<%= form_for(@general_spec) do |f| %>
  <% if @general_spec.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@general_spec.errors.count, "error") %> prohibited this general_spec from being saved:</h2>

      <ul>
      <% @general_spec.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :manufacturer_id %><br>
    <%= f.number_field :manufacturer_id %>
  </div>
  <div class="field">
    <%= f.label :vehicle_id %><br>
    <%= f.number_field :vehicle_id %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.number_field :category_id %>
  </div>
  <div class="field">
    <%= f.label :engine_type %><br>
    <%= f.text_field :engine_type %>
  </div>
  <div class="field">
    <%= f.label :engine_displacement %><br>
    <%= f.text_field :engine_displacement %>
  </div>
  <div class="field">
    <%= f.label :bore_stroke %><br>
    <%= f.text_field :bore_stroke %>
  </div>
  <div class="field">
    <%= f.label :cooling %><br>
    <%= f.text_field :cooling %>
  </div>
  <div class="field">
    <%= f.label :compression_ratio %><br>
    <%= f.text_field :compression_ratio %>
  </div>
  <div class="field">
    <%= f.label :fuel_system %><br>
    <%= f.text_field :fuel_system %>
  </div>
  <div class="field">
    <%= f.label :ignition %><br>
    <%= f.text_field :ignition %>
  </div>
  <div class="field">
    <%= f.label :starting_system %><br>
    <%= f.text_field :starting_system %>
  </div>
  <div class="field">
    <%= f.label :transmission %><br>
    <%= f.text_field :transmission %>
  </div>
  <div class="field">
    <%= f.label :final_drive %><br>
    <%= f.text_field :final_drive %>
  </div>
  <div class="field">
    <%= f.label :rake_trail %><br>
    <%= f.text_field :rake_trail %>
  </div>
  <div class="field">
    <%= f.label :seat_height %><br>
    <%= f.text_field :seat_height %>
  </div>
  <div class="field">
    <%= f.label :wheelbase %><br>
    <%= f.text_field :wheelbase %>
  </div>
  <div class="field">
    <%= f.label :front_suspension %><br>
    <%= f.text_field :front_suspension %>
  </div>
  <div class="field">
    <%= f.label :rear_suspension %><br>
    <%= f.text_field :rear_suspension %>
  </div>
  <div class="field">
    <%= f.label :front_brake %><br>
    <%= f.text_field :front_brake %>
  </div>
  <div class="field">
    <%= f.label :rear_brake %><br>
    <%= f.text_field :rear_brake %>
  </div>
  <div class="field">
    <%= f.label :front_tire %><br>
    <%= f.text_field :front_tire %>
  </div>
  <div class="field">
    <%= f.label :rear_tire %><br>
    <%= f.text_field :rear_tire %>
  </div>
  <div class="field">
    <%= f.label :fuel_capacity %><br>
    <%= f.text_field :fuel_capacity %>
  </div>
  <div class="field">
    <%= f.label :dry_weight %><br>
    <%= f.text_field :dry_weight %>
  </div>
  <div class="field">
    <%= f.label :msrp %><br>
    <%= f.number_field :msrp %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/general_specs/edit.html.erb
<h1>Editing General Spec</h1>

<%= render 'form' %>

<%= link_to 'Show', @general_spec %> |
<%= link_to 'Back', general_specs_path %>

app/views/general_specs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing General Specs</h1>

<table>
  <thead>
    <tr>
      <th>Manufacturer</th>
      <th>Vehicle</th>
      <th>Category</    th>
      <th>Engine type</th>
      <th>Engine displacement</th>
      <th>Bore stroke</th>
      <th>Cooling</th>
      <th>Compression ratio</th>
      <th>Fuel system</th>
      <th>Ignition</th>
      <th>Starting system</th>
      <th>Transmission</th>
      <th>Final drive</th>
      <th>Rake trail</th>
      <th>Seat height</th>
      <th>Wheelbase</th>
      <th>Front suspension</th>
      <th>Rear suspension</th>
      <th>Front brake</th>
      <th>Rear brake</th>
      <th>Front tire</th>
      <th>Rear tire</th>
      <th>Fuel capacity</th>
      <th>Dry weight</th>
      <th>Msrp</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @general_specs.each do |general_spec| %>
      <tr>
        <td><%= general_spec.manufacturer_id %></td>
        <td><%= general_spec.vehicle_id %></td>
        <td><%= general_spec.category_id %></td>
        <td><%= general_spec.engine_type %></td>
        <td><%= general_spec.engine_displacement %></td>
        <td><%= general_spec.bore_stroke %></td>
        <td><%= general_spec.cooling %></td>
        <td><%= general_spec.compression_ratio %></td>
        <td><%= general_spec.fuel_system %></td>
        <td><%= general_spec.ignition %></td>
        <td><%= general_spec.starting_system %></td>
        <td><%= general_spec.transmission %></td>
        <td><%= general_spec.final_drive %></td>
        <td><%= general_spec.rake_trail %></td>
        <td><%= general_spec.seat_height %></td>
        <td><%= general_spec.wheelbase %></td>
        <td><%= general_spec.front_suspension %></td>
        <td><%= general_spec.rear_suspension %></td>
        <td><%= general_spec.front_brake %></td>
        <td><%= general_spec.rear_brake %></td>
        <td><%= general_spec.front_tire %></td>
        <td><%= general_spec.rear_tire %></td>
        <td><%= general_spec.fuel_capacity %></td>
        <td><%= general_spec.dry_weight %></td>
        <td><%= general_spec.msrp %></td>
        <td><%= link_to 'Show', general_spec %></td>
        <td><%= link_to 'Edit', edit_general_spec_path(general_spec) %></td>
        <td><%= link_to 'Destroy', general_spec, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New General spec', new_general_spec_path %>

app/views/general_specs/new.html.erb
<h1>New General Spec</h1>

<%= render 'form' %>

<%= link_to 'Back', general_specs_path %>

app/views/general_specs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Manufacturer:</strong>
  <%= @general_spec.manufacturer_id %>
</p>

<p>
  <strong>Vehicle:</strong>
  <%= @general_spec.vehicle_id %>
</p>

<p>
  <strong>Category:</strong>
  <%= @general_spec.category_id %>
</p>

<p>
  <strong>Engine type:</strong>
  <%= @general_spec.engine_type %>
</p>

<p>
  <strong>Engine displacement:</strong>
  <%= @general_spec.engine_displacement %>
</p>

<p>
  <strong>Bore stroke:</strong>
  <%= @general_spec.bore_stroke %>
</p>

<p>
  <strong>Cooling:</strong>
  <%= @general_spec.cooling %>
</p>

<p>
  <strong>Compression ratio:</strong>
  <%= @general_spec.compression_ratio %>
</p>

<p>
  <strong>Fuel system:</strong>
  <%= @general_spec.fuel_system %>
</p>

<p>
  <strong>Ignition:</strong>
  <%= @general_spec.ignition %>
</p>

<p>
  <strong>Starting system:</strong>
  <%= @general_spec.starting_system %>
</p>

<p>
  <strong>Transmission:</strong>
  <%= @general_spec.transmission %>
</p>

<p>
  <strong>Final drive:</strong>
  <%= @general_spec.final_drive %>
</p>

<p>
  <strong>Rake trail:</strong>
  <%= @general_spec.rake_trail %>
</p>

<p>
  <strong>Seat height:</strong>
  <%= @general_spec.seat_height %>
</p>

<p>
  <strong>Wheelbase:</strong>
  <%= @general_spec.wheelbase %>
</p>

<p>
  <strong>Front suspension:</strong>
  <%= @general_spec.front_suspension %>
</p>

<p>
  <strong>Rear suspension:</strong>
  <%= @general_spec.rear_suspension %>
</p>

<p>
  <strong>Front brake:</strong>
  <%= @general_spec.front_brake %>
</p>

<p>
  <strong>Rear brake:</strong>
  <%= @general_spec.rear_brake %>
</p>

<p>
  <strong>Front tire:</strong>
  <%= @general_spec.front_tire %>
</p>

<p>
  <strong>Rear tire:</strong>
  <%= @general_spec.rear_tire %>
</p>

<p>
  <strong>Fuel capacity:</strong>
  <%= @general_spec.fuel_capacity %>
</p>

<p>
  <strong>Dry weight:</strong>
  <%= @general_spec.dry_weight %>
</p>

<p>
  <strong>Msrp:</strong>
  <%= @general_spec.msrp %>
</p>

<%= link_to 'Edit', edit_general_spec_path(@general_spec) %> |
<%= link_to 'Back', general_specs_path %>