config/routes.rb
Rails.application.routes.draw do
  get 'admin_users/delete'

  get 'admin_users/edit'

  get 'admin_users/index'

  get 'admin_users/new'

  get 'access/index'

  get 'access/login'

  get 'public/index'

  resources :quick_specs
  resources :general_specs
  resources :vehicles
  resources :categories
  resources :manufacturers
  devise_for :admin_users
  devise_for :users

  root "public#index"

end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
  has_one :general_spec
  has_one :quick_spec
  belongs_to :manufacturer, inverse_of: :vehicles
  belongs_to :category, inverse_of: :vehicles

  validates_presence_of :name
  validates_length_of :name, :maximum => 255
  # after_destroy :delete_related_quick_spec
  # after_destroy :delete_related_general_spec
  #
  # def delete_related_quick_spec
  #   self.quick_specs.each do |quick_spec|
  #     # Or perhaps instead of destroy, you would
  #     # move them to another page.
  #     # sections destroy
  #   end
  # end
  #
  # def delete_related_general_spec
  #   self.general_specs.each do |general_spec|
  #     # Or perhaps instead of destroy, you would
  #     # move them to another page.
  #     # sections destroy
  #   end
  # end
  #TODO: Delete Orphans

end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController

  layout 'admin'

  before_action :confirm_logged_in
  before_action :set_vehicle, only: [:show, :edit, :update, :destroy]

  # GET /vehicles
  # GET /vehicles.json
  def index
    @vehicles = Vehicle.all
  end

  # GET /vehicles/1
  # GET /vehicles/1.json
  def show
  end

  # GET /vehicles/new
  def new
    @vehicle = Vehicle.new
  end

  # GET /vehicles/1/edit
  def edit
  end

  # POST /vehicles
  # POST /vehicles.json
  def create
    @vehicle = Vehicle.new(vehicle_params)

    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully created.' }
        format.json { render :show, status: :created, location: @vehicle }
      else
        format.html { render :new }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicles/1
  # PATCH/PUT /vehicles/1.json
  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully updated.' }
        format.json { render :show, status: :ok, location: @vehicle }
      else
        format.html { render :edit }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1
  # DELETE /vehicles/1.json
  def destroy
    @vehicle.destroy
    respond_to do |format|
      format.html { redirect_to vehicles_url, notice: 'Vehicle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle
      @vehicle = Vehicle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vehicle_params
      params.require(:vehicle).permit(:name, :active, :position, :manufacturer_id, :year)
    end
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/vehicles/_form.html.erb
<%= form_for(@vehicle) do |f| %>
  <% if @vehicle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</h2>

      <ul>
      <% @vehicle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :active %><br>
    <%= f.check_box :active %>
  </div>
  <div class="field">
    <%= f.label :position %><br>
    <%= f.number_field :position %>
  </div>
  <div class="field">
    <%= f.label :manufacturer_id %><br>
    <%= f.number_field :manufacturer_id %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.text_field :year %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vehicles/edit.html.erb
<h1>Editing Vehicle</h1>

<%= render 'form' %>

<%= link_to 'Show', @vehicle %> |
<%= link_to 'Back', vehicles_path %>

app/views/vehicles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Vehicles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Active</th>
      <th>Position</th>
      <th>Manufacturer</th>
      <th>Year</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vehicles.each do |vehicle| %>
      <tr>
        <td><%= vehicle.name %></td>
        <td><%= vehicle.active %></td>
        <td><%= vehicle.position %></td>
        <td><%= vehicle.manufacturer_id %></td>
        <td><%= vehicle.year %></td>
        <td><%= link_to 'Show', vehicle %></td>
        <td><%= link_to 'Edit', edit_vehicle_path(vehicle) %></td>
        <td><%= link_to 'Destroy', vehicle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vehicle', new_vehicle_path %>

app/views/vehicles/new.html.erb
<h1>New Vehicle</h1>

<%= render 'form' %>

<%= link_to 'Back', vehicles_path %>

app/views/vehicles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @vehicle.name %>
</p>

<p>
  <strong>Active:</strong>
  <%= @vehicle.active %>
</p>

<p>
  <strong>Position:</strong>
  <%= @vehicle.position %>
</p>

<p>
  <strong>Manufacturer:</strong>
  <%= @vehicle.manufacturer_id %>
</p>

<p>
  <strong>Year:</strong>
  <%= @vehicle.year %>
</p>

<%= link_to 'Edit', edit_vehicle_path(@vehicle) %> |
<%= link_to 'Back', vehicles_path %>